"""Shared group-rank history windows and lookup tolerance."""

from __future__ import annotations

GROUP_RANK_CHANGE_CALENDAR_DAYS = {
    "1w": 7,
    "1m": 30,
    "3m": 90,
    "6m": 180,
}

GROUP_RANK_HISTORICAL_LOOKUP_TOLERANCE_DAYS = 7

DEFAULT_GROUP_RANK_HISTORY_LOOKBACK_DAYS = (
    max(GROUP_RANK_CHANGE_CALENDAR_DAYS.values())
    + GROUP_RANK_HISTORICAL_LOOKUP_TOLERANCE_DAYS
)


__all__ = [
    "DEFAULT_GROUP_RANK_HISTORY_LOOKBACK_DAYS",
    "GROUP_RANK_CHANGE_CALENDAR_DAYS",
    "GROUP_RANK_HISTORICAL_LOOKUP_TOLERANCE_DAYS",
]
